@startuml
actor Player
participant Main
participant Menu
participant CheckersGame as Game
database MyDataBase as db

Player -> Main : запуск программы
Main -> Menu : запуск игрового меню
    activate Menu
    group пользователь начинает новую игру
        Player -> Menu : нажатие на кнопку "Начать новую игру"
        Menu -> Game : запуск новой игры
        activate Game
        Game -> Game : отрисовка игрового поля
        Game -> Game : выставление шашек на начальные позиции
    else пользователь продолжает старую игру
        Player -> Menu : нажатие на кнопку "Продолжить игру"
        Menu -> Game : запуск продолжения игры
        Game -> Game : отрисовка игрового поля

        Game -> db : запрос данных о старой игре
        db -> db : загрузка данных о последней игре
        db -> Game : получение данных о последней игре

        Game -> Game : выставление шашек на позиции, полученные из БД
    end

    group процесс игры [пока у игроков есть шашки на поле]
        group перемещение шашки [корректный ход]
            Game -> Player : ожидание хода
            Player -> Game : ход
            Game -> Game : выполнение хода по координатам
            Game -> Game : обновление и отрисовка игрового поля
            Game -> Player : ожидание следующего хода
        else некорректный
            Game -> Player : ожидание хода
            Player -> Game : ход
            Game -> Game : проверка хода
            Game -> Player : ожидание следующего хода
        end
    else у одного из игроков не осталось шашек для взятия
        Game -> Game : сообщение об окончании игры и объявление победителя
        Game -> db : запрос на удаление доигранной партии из БД
        db -> db : удаление данных из БД
    end

    group пользователь хочет выйти в меню
        Player -> Game : нажатие на кнопку "Выйти в меню"
        Game -> db : запрос на сохранение текущей версии игры
        db -> db : сохранение текущей версии игры

        Game -> Menu :  выход в меню
    else пользователь хочет выйти из игры
    Player -> Game : нажатие на кнопку "Выйти из игры"
        Game -> db : запрос на сохранение текущей версии игры
        db -> db : сохранение текущей версии игры

        Game -> Main : выход из игры
        deactivate Game
    end
Menu -> Main : выход из игры
deactivate Menu
@enduml